add contributing_ja.md and contributing_en.md
Fujitsu-UTokyo-QDD/QDD pull request #23
Opened 2024-03-14 04:49 UTC by takuya576

@NT-marlowe ブランチ管理規則をcontributing.mdに記述しました。
日本語バージョンと英語バージョンを記述しました。

2024-03-14 06:04 UTC, NT-marlowe requested changes

2024-03-14 06:04 UTC, NT-marlowe commented on CONTRIBUTING_en.md
> +  - `bugfix/py-version`
technically speaking this sentence doesn't explain the convention but just provides examples.

2024-03-14 06:07 UTC, kkyusuke reviewed
いくつかコメントを追加しました。
修正する場合、英語版も同様にお願いします。

2024-03-14 06:07 UTC, kkyusuke commented on CONTRIBUTING_ja.md
> +### GitHubの無料プランで対応可能か？
この節は内部メモ的な情報なので、CONTRIBUTING.mdには不要と思います。削除を検討してください。

2024-03-14 06:07 UTC, kkyusuke commented on CONTRIBUTING_ja.md
> +- オプション1) `main` へのコミットの内容に応じてGit TagのSemVerを手動で更新します
どちらのオプションにするかを決めて、一方だけを書きたいです。

以前の議論で、とりあえずオプション1を採用し、必要に応じてオプション2に移行するという会話があったと思います。
ですので、今回はオプション1だけ書いておけばよいと考えています。修正を検討してください。

2024-03-14 06:07 UTC, kkyusuke commented on CONTRIBUTING_en.md
> +    - [git tag と GitHub の Release 機能でプロっぽさを出してみよう](https://qiita.com/tommy_aka_jps/items/5b39e4b27364c759aa53#%E3%81%A1%E3%81%AA%E3%81%BF%E3%81%AB)
enでは日本語のURLは削除してもよいかも

2024-03-15 02:32 UTC, NT-marlowe commented on CONTRIBUTING_en.md
> +    - [git tag と GitHub の Release 機能でプロっぽさを出してみよう](https://qiita.com/tommy_aka_jps/items/5b39e4b27364c759aa53#%E3%81%A1%E3%81%AA%E3%81%BF%E3%81%AB)
個人的には，これらの参考記事へのリンクはjaでもenでも不要だと思います．
そもそも内部の調査メモ的な内容であり，特にsemVerは広く浸透した概念なので，殊更に参考リンクを載せる必要性は低いと感じます．

2024-03-15 03:31 UTC, takuya576 commented on CONTRIBUTING_en.md
> +- When ready to release (e.g., bumping QDD version), pull requests from `develop` to `main` should be made.
I refrected this review.

2024-03-15 03:31 UTC, takuya576 commented on CONTRIBUTING_en.md
> +This file explains about how to contribute to our project.
I refrected this review.

2024-03-15 03:32 UTC, takuya576 commented on CONTRIBUTING_en.md
> +  - `bugfix/py-version`
I refrected this review.

2024-03-15 03:32 UTC, takuya576 commented on CONTRIBUTING_ja.md
> +### GitHubの無料プランで対応可能か？
この節の削除を行いました。

2024-03-15 03:33 UTC, takuya576 commented on CONTRIBUTING_ja.md
> +- オプション1) `main` へのコミットの内容に応じてGit TagのSemVerを手動で更新します
オプションを一つに限定しました。

2024-03-15 03:33 UTC, takuya576 commented on CONTRIBUTING_en.md
> +    - [git tag と GitHub の Release 機能でプロっぽさを出してみよう](https://qiita.com/tommy_aka_jps/items/5b39e4b27364c759aa53#%E3%81%A1%E3%81%AA%E3%81%BF%E3%81%AB)
これらのリンクはすべて削除しました。

2024-03-15 03:37 UTC, takuya576 commented
これまで頂いたレビューに対して、修正を行いました。

2024-03-15 03:53 UTC, takuya576 commented
英語版はen._mdを削除し、CONTRIBUTING.mdファイルに名前を置き換えました。

2024-03-15 04:04 UTC, NT-marlowe reviewed
英語版の方も同様に修正をお願いします．

2024-03-15 04:04 UTC, NT-marlowe commented on CONTRIBUTING_ja.md
> +  - `main` にマージされると、GitHub Actionsによって以下のアクションがトリガーされます:
GitHub Actionsの部分はこのPRでは削除して，完成したら追加するようにした方が明確で良い気がしてきました．

削除をお願いします 🙇

2024-03-15 04:04 UTC, NT-marlowe commented on CONTRIBUTING_ja.md
> +- `topic` ブランチの命名規則（暫定的）:
暫定的，は削除してよいです．

機能追加ブランチ：`feature/xxx` (e.g. `feature/add-circuit`)
バグ修正ブランチ： (同様)

のようにするのはどうでしょうか．

2024-03-15 04:43 UTC, takuya576 commented on CONTRIBUTING_ja.md
> +- `main` へのコミットの内容に応じてGit TagのSemVerを手動で更新します
修正しました。

2024-03-15 04:43 UTC, takuya576 commented on CONTRIBUTING_ja.md
> +  - `main` にマージされると、GitHub Actionsによって以下のアクションがトリガーされます:
削除しました。

2024-03-15 04:43 UTC, takuya576 commented on CONTRIBUTING_ja.md
> +- `topic` ブランチの命名規則（暫定的）:
修正しました。

2024-03-15 04:44 UTC, takuya576 commented
３度目の修正を適用しました。

2024-03-15 04:46 UTC, NT-marlowe commented on CONTRIBUTING_ja.md
> +- `main` へのコミットの内容に応じてGit TagのSemVerを手動で更新します
英語のファイルでは修正されていませんので，修正お願いします．

2024-03-15 04:58 UTC, NT-marlowe approved these changes
LGTMです．
@kkyusuke ご確認よろしくお願いいたします！

2024-03-15 05:47 UTC, merged

2024-03-15 05:47 UTC, kkyusuke commented
すべてのコメントに正しく対応出来ていると思います。
マージしました