cibuidwheelを用いてビルドを行う場合に、ローカルでもpytestが行える様に変更を加えました。
Fujitsu-UTokyo-QDD/QDD pull request #41
Opened 2024-03-27 00:46 UTC by takuya576

pyproject.tomlのproject.dependenciesの項目にpytestに必要なライブラリを加えました。
これを元にビルドしたファイルをpip installすると、pytestに必要なライブラリもinstallされます。

2024-03-27 01:37 UTC, kkyusuke commented
`project.dependencies`にすべて書き込むやり方だと、`pip install qdd`時に本来不要なソフトウェアがたくさんインストールされることになってしまいます。
このやり方以外を探してもらえませんか？

2024-03-27 01:39 UTC, kkyusuke requested changes
別の方法を模索してください。

2024-03-27 01:39 UTC, kkyusuke commented on pyproject.toml
> +    "pybind11>=2.10.4",
この部分に追加するのは望ましくないです。

2024-03-27 09:16 UTC, NT-marlowe commented on pyproject.toml
> +# This command, 'pip install {package-name}[test]',
test dependencies をいっぺんにインストールするコマンドなのに，なぜpackage-nameを指定する必要があるのでしょうか？
実際に実行するコマンドの例を知りたいです．

2024-03-27 09:27 UTC, takuya576 commented on pyproject.toml
> +[project.optional-dependencies]
project.optional-dependenciesにpytest用のライブラリを加えました。
インストール時にpytestを必要としない人は、以下のコマンドでインストールできます。
```shell
pip install {QDD_DIR}/dist/qdd-XXX.whl
``` 
pytestが必要な開発環境としてインストールする人は、[test]をキーとして指定することでpytestに必要なモジュールを含めてインストールできます。
```shell
pip install {QDD_DIR}/dist/qdd-XXX.whl[test]
```

2024-03-27 09:27 UTC, takuya576 commented on pyproject.toml
> +# This command, 'pip install {package-name}[test]',
すみません、表現方法が不適切でした。
該当部分にコメントした様に
```shell
pip install {QDD_DIR}/dist/qdd-XXX.whl[test]
``` 
を実行します。
package-nameはwheelファイルのことを意図していました。

2024-03-28 08:38 UTC, kkyusuke commented
私の方で修正をリクエストしているので、マージできない状態だと思います。
再レビュー可能になったら教えてください。

2024-03-29 10:21 UTC, kkyusuke approved these changes

2024-03-29 10:23 UTC, kkyusuke commented
LGTMです。
@NT-marlowe 確認いただき、問題なければマージお願いします

2024-03-29 11:20 UTC, merged