Feature/add gates
Fujitsu-UTokyo-QDD/QDD pull request #63
Opened 2024-08-08 06:56 UTC by Kotani-UT

basis gate でコメントアウトされていたゲートを追加しました。
rotation + muticontros のゲートに関しては実装できますが、qiskitにないのでスキップしています。
追加で_eval_circuit内のDD作成部分をリファクタリングしました。
具体的には全てのゲートに対して matrix,controls作成->gate作成->gate追加の流れに統一しました。

2024-08-09 05:13 UTC, Kotani-UT commented
qdd_backend.py内で2量子ビットゲートの追加部分を修正しました。元のコードでは量子ビットレジスタの指定が反対になっていたため、rzxゲートを含むゲートにおいてテストにこけていました。
dd.cpp内のユニタリゲート作成のためのmakeLargeGateの再帰の終端部分のコードを修正しました。

2024-08-14 09:47 UTC, kkyusuke requested changes
コメントしました。いくつか重いコメントが多いと思うので、ゆっくり取り組んでいただければと思います。

2024-08-14 09:47 UTC, kkyusuke commented on qdd/qdd_backend.py
> +                            controls.append(self.get_qID(qargs[j]))
Qiskitの仕様上は、_control_gateでなくても（例えばXゲートだったとしても）、qargsに2つ以上の引数が与えられて事実上の制御ゲート（例の場合、CXやMCX）になることがあり得ると思います。

この実装ではそのような場合はケアできていない？
そもそもケアすべきかどうかも含めて、意見を聞かせてほしいです。

2024-08-14 09:47 UTC, kkyusuke commented on qdd/qdd_backend.py
> +                                controls.append(map_after_swap[self.get_qID(qargs[j])])
同上です

2024-08-14 09:47 UTC, kkyusuke commented on src/dd.cpp
> -}
このmakeSwapはSwapゲート作成に特化して軽量化されているので、このまま使用してもらいたいです。

2024-08-14 09:47 UTC, kkyusuke commented on test/python/test_gate.py
> +            qdd_mat = pyQDD.makeGate(num_qubits, qdd(para1, para2, para3), num_qubits-1, controls).getEigenMatrix()
num_qubits=5とかにして、Target qubitとcontrolsをランダムに決めることは出来ますか？
（他のゲートも同様）

2024-08-20 05:17 UTC, Kotani-UT commented on qdd/qdd_backend.py
> -    qiskit_gates.UGate: pyQDD.u,
qiskit_algorithmsでu2が使われているので、単純にu1,u2,u3を外すとテストが通らなくなります。
特にu1,u2,u3をサポートして悪い副作用はないとは思うので、qiskit_algorithmsをテストコードから完全に
排除するまでは残しておいてよいと思います。

2024-08-20 05:17 UTC, Kotani-UT commented on qdd/qdd_backend.py
> +            "unitary", # HOW TO ???
消します

2024-08-20 05:17 UTC, Kotani-UT commented on qdd/qdd_backend.py
u1,u2,u3の件と合わせてテストコードの変更を別のプルリクエストですればよいでしょうか

2024-08-20 05:18 UTC, Kotani-UT commented on src/dd.cpp
> +    }
参考にした
https://github.com/cda-tum/mqt-core/blob/5be1c3ec4efb773d0330298621704e876afa7c16/include/mqt-core/dd/Package.hpp#L493
ではIゲートを返す実装なので、そのままにしましたが別段どちらでもよい気がします。

2024-08-20 05:19 UTC, Kotani-UT commented on src/dd.cpp
> -}
復活させます

2024-08-20 05:19 UTC, Kotani-UT commented on test/python/test_gate.py
> +            qdd_mat = pyQDD.makeGate(num_qubits, qdd(para1, para2, para3), num_qubits-1, controls).getEigenMatrix()
現状の行列を比較する方法ではなく、QuantumCircuitにビット位置を指定して追加しsamplerで値を比較するといった方法でならできます。

2024-08-20 05:41 UTC, Kotani-UT commented on qdd/qdd_backend.py
> +                            controls.append(self.get_qID(qargs[j]))
ケアはできていないです。
そもそもbase_classがXGateでqargsが2つ以上のゲートをqiskit側で追加する方法がわからないので、
ケアする必要があるかはわかりません。
ただ_control_gateにあるか否かに関わらずtarget以外をcontrolsに追加すればよいので対応は簡単です。
どうしましょう？

2024-08-20 05:50 UTC, kkyusuke commented on qdd/qdd_backend.py
> +                            controls.append(self.get_qID(qargs[j]))
対応をお願いします

2024-08-20 05:50 UTC, kkyusuke commented on test/python/test_gate.py
> +            qdd_mat = pyQDD.makeGate(num_qubits, qdd(para1, para2, para3), num_qubits-1, controls).getEigenMatrix()
はい、それでお願いします

2024-08-20 05:52 UTC, kkyusuke commented on qdd/qdd_backend.py
> +                        matrix = i.to_matrix()
> そもそもサイズは大きいが0の多い行列を表せるというDDのメリットの話なら、関数入力の方からC++側のコードを少し考えなおします。

まさにこのあたりのことを考えていました。なにかアイデアありますか？

2024-08-20 06:02 UTC, Kotani-UT commented on qdd/qdd_backend.py
> +                        matrix = i.to_matrix()
入力を行列の代わりに(i,j)成分を表す関数にするのが汎用性が高いかなと思います。
大きいゲートを利用したいとしても少なくともユーザーとしては紙とペンでなら簡単に書けるものだと思うので。

2024-08-21 02:02 UTC, kkyusuke commented on qdd/qdd_backend.py
はい、それで大丈夫です。やりやすい方法でお任せします

2024-08-21 02:09 UTC, kkyusuke commented on qdd/qdd_backend.py
> +                        matrix = i.to_matrix()
すみません、Qiskitのunitary()関数を使うことは前提にした方が良さそうです。

ちょっと会話中で勘違いをしていたので話を戻します。
unitary()関数では、例えば1量子ゲートの場合は「ターゲットbit」と「2x2行列」を与えると思います。この時点では、メモリは問題になりません。
しかし、`i.to_matrix()`の部分では、回路全体に対するユニタリ行列が生成される(?)はずなので、1量子ゲートだったとしても、Nbit量子回路の場合には2^Nx2^Nのユニタリ行列が生成されると思います。これはOoMになりそうです。これを懸念しています。

2024-08-21 05:47 UTC, Kotani-UT commented on qdd/qdd_backend.py
> +                        matrix = i.to_matrix()
ここでのiはQuantumCircuit.dataリストの要素で回路内のゲートや命令を指しています。
i.to_matrix()の部分では回路全体ではなくゲート単位での行列が返ってくるので大丈夫だと思います。
実際10量子ビット回路に3量子ビットユニタリゲートを加えて、backendを走らせてi.to_matrix()を確認すると
8x8行列が返ってきていました。

2024-08-22 11:03 UTC, kkyusuke commented on qdd/qdd_backend.py
> +                        matrix = i.to_matrix()
なるほど、ありがとうございます。
そうなってくると、`gate = pyQDD.unitary(matrix)`で生成した決定グラフは量子回路のビット数分の情報がないので、そのまま次の行でmv_multiplyしてはいけないです。
修正できそうでしょうか？

2024-08-28 04:19 UTC, Kotani-UT commented
コメントで指摘された部分を修正しました。
追加でmakeTwoQubitGateのコントロールの追加に間違いがあったので修正しました。
またunitaryに対応しましたがかなり動作が遅いです。
ユニタリゲートは分解前提な気がします。

2024-08-28 13:10 UTC, kkyusuke commented on qdd/qdd_backend.py
> +            "unitary",
かなり遅いとのことなので、unitaryはコメントアウトしてください。
（コードを修正してもらって恐縮ですが･･･。必要な時に手動で追加はできるはずなので）

2024-08-29 01:24 UTC, kkyusuke approved these changes

2024-08-29 01:27 UTC, merged

2024-08-29 01:30 UTC, kkyusuke commented
次のPRでは、Resolveになっていないコメントに取り組みをお願いします